Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -17,22 +17,23 @@ jobs:
           name: echo "this is the test job"
           command: |
             # Current version via self-updating btctl grabbing the latest version
-            CURRENT_VERSION=btctl-v1.0.0
-            echo "Current btctl release version: $CURRENT_VERSION"
-            
-            # Extract the version part and split to major/minor/patch
-            VERSION_PART=$(echo "$CURRENT_VERSION" | sed "s/^btctl-v\([0-9]*\.[0-9]*\.[0-9]*\)$/\1/")
-            echo $VERSION_PART
-            IFS='.' read -r MAJOR MINOR PATCH \<<< "$(echo "$VERSION_PART")"
-            
-            # Increment the minor version
-            MINOR_NEW=$((MINOR + 1))
-            
-            # Save the new version
-            echo "export BTCTL_VERSION=btctl-v$MAJOR.$MINOR_NEW.$PATCH" >> $BASH_ENV
-            source $BASH_ENV
-            echo "New version to use: $BTCTL_VERSION"
-      - run: echo $BTCTL_VERSION       
+            LATEST_VERSION=v1.0.4
+            VERSION_REGEX="^v([0-9]+)\.([0-9]+)\.([0-9]+)$"
+            if [[ $LATEST_VERSION =~ $VERSION_REGEX ]]; then
+              MAJOR="${BASH_REMATCH[1]}"
+              MINOR="${BASH_REMATCH[2]}"
+              PATCH="${BASH_REMATCH[3]}"
+              NEW_VERSION="v${MAJOR}.$((MINOR+1)).0"
+              echo "New version: $NEW_VERSION"
+              echo $NEW_VERSION > new_version.txt
+            else
+              echo "Error: Unable to parse the latest version"
+              exit 1
+            fi
+      - persist_to_workspace:
+          root: .
+          paths:
+            - new_version.txt    
 
 # Orchestrate our job run sequence
 workflows:
